# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Overview"
  url = "#about"
  weight = 1

[[main]]
  name = "Resume"
  url = "resume"
  weight = 2

[[main]]
  name = "Curriculum Vitae"
  url = "cv"
  weight = 3

[[main]]
  name = "Physics Publications"
  url = "physics_pubs"
  weight = 4

[[main]]
  name = "Computing Publications"
  url = "computing_pubs"
  weight = 5

[[main]]
  name = "Talks"
  url = "talks"
  weight = 6

[[main]]
  name = "Articles"
  url = "articles"
  weight = 7

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
